participant Client as c
participant Server as s

c->s: OPTIONS /events HTTP/1.1
note over c, s:
Host: example.com
...
end note

s-->c: HTTP/1.1 204 No Content
note over s, c:
Allow: GET, OPTIONS
Accept: application/ld+json
EPCIS-min: 2.0
EPCIS-max: 2.0
CBV-version: 1.0
EPCIS-extensions: example-epc-ext:<http://example.com/epcis>
Vendor-version: example-version-1.0
CBV-extensions: ex1: <http://example.com/>, vendor1: <http://example.org/defs#>
...
end note
c->s: GET /events HTTP/1.1
note over c, s:
Host: example.com
Content-Type: application/ld+json
EPCIS-version: 2.0
...
end note
s-->c: HTTP/1.1 200 OK
note over c, s:
EPCIS-version: 2.0
Content-Type: application/ld+json
Content-Length: 2051
...
{
    "@context": "https://id.gs1.org/epcis-context.jsonld",
    "isA": "EPCISDocument",
    "creationDate": "2019-13-06T11:30:47+00:00",
    "format": "application/ld+json",
    "epcisBody": {
      "eventList": [
        {
          "eventID": "oe1",
...
}
end note