participant Client as c
participant Server as s

c->s: OPTIONS /queries/myQuery HTTP/1.1
note over c, s:
Host: example.com
...
end note

s-->c: HTTP/1.1 204 No Content
note over s, c:
Allow: GET, OPTIONS
Accept: application/ld+json
GS1-EPCIS-Min: 2.0
GS1-EPCIS-Max: 2.0
GS1-CBV-Version: 1.0
GS1-EPCIS-Extensions: {"example-epc-ext":"https://example.com/epcis"}
GS1-Vendor-Version: "example-version-1.0"
GS1-CBV-Extensions: {"ex1": "https://example.com/", "vendor1": "https://example.org/defs#"}
...
end note
c->s: GET /queries/myQuery/events HTTP/1.1
note over c, s:
Host: example.com
Content-Type: application/ld+json
GS1-EPCIS-version: 2.0
...
end note
s-->c: HTTP/1.1 200 OK
note over c, s:
GS1-EPCIS-version: 2.0
Content-Type: application/ld+json
Content-Length: 2051
...
{
    "@context": "https://example.com/epcis-context.jsonld",
    "type": "EPCISDocument",
    "creationDate": "2019-13-06T11:30:47+00:00",
      "epcisBody": {
      "eventList": [
        {
          "eventID": "urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
...
}
end note
