title Query Subscriptions
Client->Server: POST /queries/query1/subscriptions
note over Client,Server: 
Request Body
{
	{
  "dest": "https://client.example.com/queryCallback",
  "signatureToken": "13df38d8275b13f05704629e5f1cf3d45d6132d5",
  "reportIfEmpty": true,
  "schedule": {
    "hour":"1",
    "minute": "5"
  }
}
end note
alt: Subscription successful
Server-->Client: 201 Created \n Location:https://example.com/queries/query1/subscriptions/42
else: Query does not exist
Server-->Client: 404 NoSuchResourceException
else: Other EPCIS Exceptions
Server-->Client: 40X ...
end
Server->+Server: onEvent
Server->+Client: POST to https://client.example.com/queryCallback
note over Server, Client:
{
    "@context": ...
    "type": "EPCISQueryDocument",
    "creationDate": "2022-07-11T11:30:47+00:00",
    "schemaVersion": 2.0,
      "epcisBody": {
      "queryResults": {....
        
end note
Client-->-Server: 200 success
Server-->-Server:
Server->+Server: onError
Server->+Client: POST https://client.example.com/queryCallback \n An EPCIS error
Client-->Server: 200 success
Server-->-Server: onEvent ...