title Query Subscriptions
Client->Server: POST /queries/query1/subscriptions?trigger=query1&query2
note over Client,Server: 
Request Body
{
	eventUrl:https://client/onEvent
	errorUrl:https://client/onError
}
end note
alt: Subscription successful
Server-->Client: 201 Created \n Location:https://server/queries/query1/subscriptions/42
else: Trigger query too long
Server-->Client: 414 QueryTooComplexException
else: Query does not exist
Server-->Client: 404 NoSuchNameException
else: Other EPCIS Exceptions
Server-->Client: 400 ...
end
Server->+Server: onEvent
Server->+Client: POST /onEvent
note over Server, Client:
{
    "@context": "https://www.gs1.org/docs/epc/epcis_2_0_draft_schema_20200713/EPCIS-2.0-context.jsonld",
    "type": "EPCISDocument",
    "creationDate": "2019-07-11T11:30:47+00:00",
    "schemaVersion": 1.2,
      "epcisBody": {
      "eventList": [
        {
          "eventID": "oe1",
          ...}]}}
end note
Client-->-Server: 200 success
Server-->-Server:
Server->+Server: onError
Server->+Client: POST /onError \n An EPCIS error
Client-->Server: 200 success
Server-->-Server:
