participant Client as c
participant Server as s

c->s: POST https://example.com/queries/MyQuery
note over Client, Server:
{
  "query": {
    "EQ_bizStep": [
      "urn:epcglobal:cbv:bizstep:shipping",
      "urn:epcglobal:cbv:bizstep:receiving"
    ],
    "eventTypes": "ObjectEvent"
  },
  "queryType": "events"
}
end note
c->s: POST https://example.com/queries/MyQuery/subscriptions
note over Client, Server:
{
  "callbackUrl": "https://client.example.com/queryCallback",
  "secret": "0435ojtojt02",
  "schedule": {
    "hour": "1",
    "minute": "5"
  }
}
end note
s-->c: {"subscriptionId": "df5a33e3-5aa3-4403-ae01-99b83234e27b"}
s->s: CuckooClock()
note left of s: The time is 01:05h
s->c:  POST https://client.example.com/queryCallback?secret=0435ojtojt02
note over Client, Server:
{..., "bizStep": "urn:epcglobal:cbv:bizstep:shipping",...}
end note
c->s: DELETE  https://client.example.com/queries/MyQuery/subsriptions/df5a33e3-5aa3-4403-ae01-99b83234e27b