participant Client as c
participant Server as s

c->s: POST https://example.com/queries/MyQuery
note over Client, Server:
{
  "query": {
    "EQ_bizStep": [
      "shipping",
      "receiving"
    ],
    "eventTypes": "ObjectEvent"
  },
  "queryType": "events"
}
end note
c->s: GET https://example.com/queries/MyQuery/events?minute=5&hour=1
note over Client, Server:
Host: example.com
Upgrade: websocket
Connection: Upgrade
end note
s-->c: HTTP/1.1 101 Switching Protocols
note over Server, Client:
Upgrade: websocket
Connection: Upgrade
Switch from
end note
s->s: CuckooClock()
note left of s: The time is 01:05h
s<->c: wss://example.com/queries/MyQuery/events?minute=5&hour=1
note over Client, Server:
{..., "bizStep": "shipping",...}
end note
c->s: close() 
